Repository chili-publish/studio-sdk, pull requests merged in 2022-12, with the labels that each got.

#216 [Fix] Correct upload pipeline
  .github/workflows/pr-build.yml
  .github/workflows/publish-package.yml
  .github/workflows/publish-release-npm.yml
Labels: bug

#219 [Feature] Add `setVariableSource` and `removeVariableSource` SDK methods
  src/controllers/VariableController.ts
  src/tests/__mocks__/MockEditorAPI.ts
  src/tests/controllers/VariableController.test.ts
  types/VariableTypes.ts
Labels: ready for review

#223 [Feature] Bump engine version to 0.0.23
  editor-engine.json
Labels: dependencies
