Repository chili-publish/studio-sdk, pull requests merged in 2023-06, with the labels that each got.

#287 [Fix] Actions Trigger Typing more strict
  src/types/ActionTypes.ts
Labels: documentation

#290 [Fix] Layout action typing issue
  types/Actions.d.ts
Labels: bug

#294 [Fix] make methods show up as `method` in Action typings
  types/Actions.d.ts
Labels: bug

#308 [Fix] Restore breaking change in setImageFromConnector
  src/controllers/FrameController.ts
  src/tests/controllers/FrameController.test.ts
Labels: bug

#303 [Fix] make setTool public
  src/controllers/ToolController.ts
Labels: CS Wishlist

#304 [Feature] Create environment base url
  src/controllers/UtilsController.ts
  src/index.ts
  src/tests/controllers/UtilsController.test.ts
  src/utils/enums.ts
Labels: CS Wishlist
