Repository chili-publish/studio-sdk, pull requests merged in 2023-09, with the labels that each got.

#341 [Fix] Loosen node rules for newer versions
  package.json
Labels: dependencies

#344 [Fix] rename engine to info to be consistent
  src/sdk.ts
Labels: bug

#347 [Feature] [EDT-1091] Connector instance per image variable
  src/controllers/ConnectorController.ts
  src/controllers/UndoManagerController.ts
  src/controllers/VariableController.ts
  src/sdk.ts
  src/tests/controllers/ConnectorController.test.ts
  src/tests/controllers/UndoManagerController.test.ts
  src/tests/controllers/VariableController.test.ts
  src/types/ConnectorTypes.ts
Labels: Breaking Changes

#337 [Feature] [EDT-1088] Return connector options from connector
  src/controllers/FontConnectorController.ts
  src/controllers/MediaConnectorController.ts
  src/tests/controllers/ConnectorController.test.ts
  src/tests/controllers/FontConnectorController.test.ts
  src/tests/controllers/MediaConnectorController.test.ts
  src/types/CommonTypes.ts
  src/types/ConnectorTypes.ts
  types/Connector.Shared.d.ts
  types/FontConnector.d.ts
  types/MediaConnector.d.ts
Labels: Breaking Changes

#350 [Feature] [EDT-1148] Connector & State getter refactor
  src/controllers/ConnectorController.ts
  src/tests/controllers/ConnectorController.test.ts
Labels: Breaking Changes

#356 [Feature] Font families
  packages/sdk/src/controllers/FontConnectorController.ts
  packages/sdk/src/controllers/FontController.ts
  packages/sdk/src/controllers/SubscriberController.ts
  packages/sdk/src/index.ts
  packages/sdk/src/interactions/connector.ts
  packages/sdk/src/sdk.ts
  packages/sdk/src/tests/__mocks__/config.ts
  packages/sdk/src/tests/controllers/FontConnectorController.test.ts
  packages/sdk/src/tests/controllers/FontController.test.ts
  packages/sdk/src/tests/controllers/SubscriberContoller.test.ts
  packages/sdk/src/types/CommonTypes.ts
  packages/sdk/src/types/FontConnectorTypes.ts
  packages/sdk/src/types/FontTypes.ts
Labels: Breaking Changes
