Repository chili-publish/studio-sdk, pull requests merged in 2023-08, with the labels that each got.

#326 [Feature] Release bump engine to 0.1.6
  editor-engine.json
Labels: ready to merge

#316 [Feature] Remove url variable source
  src/controllers/VariableController.ts
  src/index.ts
  src/tests/controllers/VariableController.test.ts
  src/types/FrameTypes.ts
  src/types/VariableTypes.ts
Labels: Breaking Changes

#333 [Feature] Bump engine 0.1.7 for release
  editor-engine.json
Labels: dependencies

#327 [Feature] Visibility naming
  src/controllers/FrameController.ts
  src/tests/__mocks__/FrameProperties.ts
  src/tests/__mocks__/mockDocument.ts
  src/tests/controllers/FrameController.test.ts
  src/types/CommonTypes.ts
  src/types/DocumentTypes.ts
  src/types/FrameTypes.ts
  src/types/LayoutTypes.ts
  types/Actions.d.ts
Labels: Breaking Changes
