Repository chili-publish/studio-sdk, pull requests merged in 2024-07, with the labels that each got.

#478 [EDT-1538] Next.ConnectorGrafxRegistration added to avoid breaking changes
  packages/sdk/src/controllers/ConfigurationController.ts
  packages/sdk/src/controllers/ConnectorController.ts
  packages/sdk/src/controllers/SubscriberController.ts
  packages/sdk/src/controllers/VariableController.ts
  packages/sdk/src/next/NextInitiator.ts
  packages/sdk/src/next/controllers/ConnectorController.ts
  packages/sdk/src/next/controllers/SubscriberController.ts
  packages/sdk/src/next/controllers/VariableController.ts
  packages/sdk/src/next/index.ts
  packages/sdk/src/next/tests/controllers/ConnectorController.test.ts
  packages/sdk/src/next/tests/controllers/SubscriberContoller.test.ts
  packages/sdk/src/next/tests/controllers/VariableController.test.ts
  packages/sdk/src/next/types/ConnectorTypes.ts
  packages/sdk/src/next/types/VariableTypes.ts
  packages/sdk/src/sdk.ts
  packages/sdk/src/tests/__mocks__/localConfig.ts
  packages/sdk/src/tests/controllers/ConfigurationConnectorController.test.ts
  packages/sdk/src/tests/controllers/ConnectorController.test.ts
  packages/sdk/src/tests/controllers/SubscriberContoller.test.ts
  packages/sdk/src/tests/controllers/VariableController.test.ts
  packages/sdk/src/tests/utils/ConnectorCompatibilityTools.test.ts
  packages/sdk/src/tests/utils/LocalConfigurationDecorator.test.ts
  packages/sdk/src/types/ConnectorTypes.ts
  packages/sdk/src/utils/ConnectorCompatibilityTools.ts
  packages/sdk/src/utils/LocalConfigurationDecorator.ts
Labels: v2

#487 [Fix] SDK Versioning strategy update
  .github/workflows/pr-merge.yml
  .github/workflows/publish-release-npm.yml
Labels: documentation, dependencies

#488 [Fix] Add auth for bump
  .github/workflows/pr-merge.yml
Labels: bug, setup

#489 [Fix] Add gh token
  .github/workflows/pr-merge.yml
Labels: bug

#494 [Fix] Switch prerelease to patch on release
  .github/workflows/publish-release-npm.yml
Labels: bug
