Repository chili-publish/studio-sdk, pull requests merged in 2025-02, with the labels that each got.

#563 [Fix] Update license
  LICENSE
Labels: documentation

#560 [Feature] [EDT-1756] Add available for user property to layouts
  packages/sdk/src/controllers/LayoutController.ts
  packages/sdk/src/tests/controllers/LayoutController.test.ts
  packages/sdk/src/types/LayoutTypes.ts
Labels: Ready for QA

#565 [Feature] Add setSelectedByUser
  packages/sdk/src/controllers/LayoutController.ts
  packages/sdk/src/tests/controllers/LayoutController.test.ts
  packages/sdk/src/types/LayoutTypes.ts
Labels: Ready for QA

#549 [EDT-1765] SnapshotSettings introduced
  packages/sdk/src/controllers/PageController.ts
  packages/sdk/src/tests/controllers/PageController.test.ts
  packages/sdk/src/types/PageTypes.ts
Labels: Ready for QA

#566 [Feature] [EDT-1817] [Snapshot] Define maximum time to wait for assets to be loaded
  packages/sdk/src/types/PageTypes.ts
Labels: Ready for QA

#562 [Feature][EDT-1801] Add calculated variable visibility
  packages/actions/src/ActionHelpers.ts
  packages/actions/types/Actions.d.ts
  packages/sdk/src/controllers/VariableController.ts
  packages/sdk/src/index.ts
  packages/sdk/src/next/tests/controllers/VariableController.test.ts
  packages/sdk/src/tests/controllers/VariableController.test.ts
  packages/sdk/src/types/DocumentTypes.ts
  packages/sdk/src/types/VariableTypes.ts
  types/Actions.d.ts
Labels: Ready for QA

#569 [Feature][EDT-1801] Fix wrong api method/SDK contract
  packages/sdk/src/controllers/VariableController.ts
  packages/sdk/src/tests/controllers/VariableController.test.ts
Labels: Ready for QA

#570 [Fix][EDT-1801] Fix wrongly removed property
  packages/sdk/src/controllers/VariableController.ts
  packages/sdk/src/next/tests/controllers/VariableController.test.ts
  packages/sdk/src/tests/controllers/VariableController.test.ts
  packages/sdk/src/types/VariableTypes.ts
Labels: Ready for QA

#567 [Feature] Add resizableByUser
  packages/sdk/src/controllers/LayoutController.ts
  packages/sdk/src/index.ts
  packages/sdk/src/tests/controllers/CharacterStyleController.test.ts
  packages/sdk/src/tests/controllers/LayoutController.test.ts
  packages/sdk/src/types/LayoutTypes.ts
Labels: Ready for QA

#568 [Fix] Automate version management and add workflow for manual update
  .github/workflows/publish-release-npm.yml
  .github/workflows/update-engine-version.yml
Labels: documentation, enhancement, Ready for QA

#572 [Release] Prep for 1.20
  package.json
  packages/actions/package.json
  packages/connectors/package.json
  packages/sdk/editor-engine.json
  packages/sdk/package.json
  packages/sdk/src/tests/controllers/VariableController.test.ts
  packages/sdk/src/types/PageTypes.ts
Labels: Ready for QA

#573 [Fix] Docs fix publish
  .github/workflows/publish-docs.yml
Labels: dependencies

#574 [Fix] [WRS-3252] Upgrade ts
  packages/sdk/package.json
  packages/sdk/yarn.lock
Labels: Ready for QA

#557 [Feature] [EDT-1761] Add override states on horizontal/vertical anchors
  packages/sdk/src/types/CommonTypes.ts
  packages/sdk/src/types/FrameTypes.ts
Labels: Ready for QA

#579 [Fix] Automated version management parameters
  .github/workflows/publish-release-npm.yml
Labels: Ready for QA

#571 [Fix] Add keepPageSize parameter
  packages/actions/src/ActionHelpers.ts
  packages/actions/types/Actions.d.ts
  types/Actions.d.ts
Labels: Ready for QA
